import { createReactComponent } from './utils';

export const UniBackdrop = /*@__PURE__*/createReactComponent('uni-backdrop');
export const UniBarText = /*@__PURE__*/createReactComponent('uni-bar-text');
export const UniButton = /*@__PURE__*/createReactComponent('uni-button');
export const UniCheckbox = /*@__PURE__*/createReactComponent('uni-checkbox');
export const UniComboGroup = /*@__PURE__*/createReactComponent('uni-combo-group');
export const UniComboItem = /*@__PURE__*/createReactComponent('uni-combo-item');
export const UniComboText = /*@__PURE__*/createReactComponent('uni-combo-text');
export const UniDialogActions = /*@__PURE__*/createReactComponent('uni-dialog-actions');
export const UniDialogContent = /*@__PURE__*/createReactComponent('uni-dialog-content');
export const UniDialogTitle = /*@__PURE__*/createReactComponent('uni-dialog-title');
export const UniErrors = /*@__PURE__*/createReactComponent('uni-errors');
export const UniExpandableField = /*@__PURE__*/createReactComponent('uni-expandable-field');
export const UniOutsideClick = /*@__PURE__*/createReactComponent('uni-outside-click');
export const UniProgressLinear = /*@__PURE__*/createReactComponent('uni-progress-linear');
export const UniRadioController = /*@__PURE__*/createReactComponent('uni-radio-controller');
export const UniSelect = /*@__PURE__*/createReactComponent('uni-select');
export const UniTagChip = /*@__PURE__*/createReactComponent('uni-tag-chip');
export const UniTextField = /*@__PURE__*/createReactComponent('uni-text-field');
export const UniTooltip = /*@__PURE__*/createReactComponent('uni-tooltip');
export const UniUnderline = /*@__PURE__*/createReactComponent('uni-underline');
