/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface UniBarText {}
  interface UniButton {}
  interface UniHero {
    'backgroundUrl'?: string;
  }
}

declare global {


  interface HTMLUniBarTextElement extends Components.UniBarText, HTMLStencilElement {}
  var HTMLUniBarTextElement: {
    prototype: HTMLUniBarTextElement;
    new (): HTMLUniBarTextElement;
  };

  interface HTMLUniButtonElement extends Components.UniButton, HTMLStencilElement {}
  var HTMLUniButtonElement: {
    prototype: HTMLUniButtonElement;
    new (): HTMLUniButtonElement;
  };

  interface HTMLUniHeroElement extends Components.UniHero, HTMLStencilElement {}
  var HTMLUniHeroElement: {
    prototype: HTMLUniHeroElement;
    new (): HTMLUniHeroElement;
  };
  interface HTMLElementTagNameMap {
    'uni-bar-text': HTMLUniBarTextElement;
    'uni-button': HTMLUniButtonElement;
    'uni-hero': HTMLUniHeroElement;
  }
}

declare namespace LocalJSX {
  interface UniBarText {}
  interface UniButton {}
  interface UniHero {
    'backgroundUrl'?: string;
  }

  interface IntrinsicElements {
    'uni-bar-text': UniBarText;
    'uni-button': UniButton;
    'uni-hero': UniHero;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'uni-bar-text': LocalJSX.UniBarText & JSXBase.HTMLAttributes<HTMLUniBarTextElement>;
      'uni-button': LocalJSX.UniButton & JSXBase.HTMLAttributes<HTMLUniButtonElement>;
      'uni-hero': LocalJSX.UniHero & JSXBase.HTMLAttributes<HTMLUniHeroElement>;
    }
  }
}


