name: Main CI Pipeline

on:
  push:
    # Currently, disable the path restrictions so that we get passing tests when nothing changes
    branches: [ master ]
#    paths: [ 'core/**' ]
  pull_request:
    branches: [ master ]
#    path: [ 'core/**' ]

jobs:
  # This jobs essentially clones the repo, installs all the deps, and saves the result in the cache as $SHA-project
  install:
    runs-on: ubuntu-latest
    steps:
      # Clone the repository to $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
        with:
          fetch-depth: 20
          persist-credentials: false

      # Cache deps for a faster install
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      # Install root deps (Just lerna CLI at the moment)
      - run: npm ci

      # Install dependencies in all packages with lerna
      - run: ./node_modules/.bin/lerna bootstrap

      # Cache the result of the install
      - uses: actions/cache@v2
        id: cache-project
        with:
          path: ./*
          key: ${{ github.sha }}-project

  # Fail fast, check that the new code looks good
  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      # Restore the project
      - uses: actions/cache@v2
        id: restore-project
        with:
          path: ./*
          key: ${{ github.sha }}

      # Let each package lint itself
      - run: ./node_modules/.bin/lerna run lint

  # Builds the @unicorndesign/core package, and saves it as $SHA-core
  build-core:
    runs-on: ubuntu-latest
    needs: install
    steps:
      # Restore the project
      - uses: actions/cache@v2
        id: restore-project
        with:
          path: ./*
          key: ${{ github.sha }}

      # Builds @unicorndesign/core
      - name: Build Core
        run: npm run build
        working-directory: ./core

      # Saves build artifacts
      - uses: actions/cache@v2
        id: cache-build
        with:
          path: |
            ./core/dist/*
            ./core/loader/*
          key: ${{ github.sha }}-core

  # Tests @unicorndesign/core
  test-core:
    name: Test core
    runs-on: ubuntu-latest
    needs: install
    steps:
      # Restore the project
      - uses: actions/cache@v2
        id: restore-project
        with:
          path: ./*
          key: ${{ github.sha }}

      # Execute tests
      - name: Run tests
        run: npm test
        working-directory: ./core

  # Tests @unicorndesign/react
  test-react:
    name: Test react
    runs-on: ubuntu-latest
    needs: [install, build-core]
    steps:
      # Load up the project
      - uses: actions/cache@v2
        id: restore-project
        with:
          path: ./*
          key: ${{ github.sha }}

      # Load the core build artifacts (build:storybook needs these)
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: |
            ./core/dist/*
            ./core/loader/*
          key: ${{ github.sha }}-core

      # Link packages, so that react will use the latest core version
      - run: ./node_modules/.bin/lerna link

      # Test react
      - run: npm run build
        working-directory: ./packages/react

  # Upload the build to chromatic for additional visual testing
  chromatic:
    name: Upload to Chromatic
    runs-on: ubuntu-latest
    needs: [install, build-core]
    steps:
      # Load up the project
      - uses: actions/cache@v2
        id: restore-project
        with:
          path: ./*
          key: ${{ github.sha }}

      # Load the core build artifacts
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: |
            ./core/dist/*
            ./core/loader/*
          key: ${{ github.sha }}-core

      # Upload to Chromatic
      - name: Run Chromatic
        run: npm run chromatic -- --auto-accept-changes master --exit-zero-on-changes
        working-directory: ./core
        env:
          CHROMATIC_APP_CODE: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

  # Merges all the tests together into one check
  passed-tests:
    name: Check nothing is on fire
    runs-on: ubuntu-latest
    needs: [lint, test-core, test-react]
    steps:
      - run: exit 0

  # Publish website (packages/site & storybook)
  publish-site:
    name: Publish Site
    runs-on: ubuntu-latest
    needs: passed-tests
    steps:
      # Load up the project
      - uses: actions/cache@v2
        id: restore-project
        with:
          path: ./*
          key: ${{ github.sha }}

      # Load the core build artifacts (build:storybook needs these)
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: |
            ./core/dist/*
            ./core/loader/*
          key: ${{ github.sha }}-core

      # Builds a static storybook
      - name: Build Storybook
        run: npm run build:storybook
        working-directory: ./core

      # Shuffles around files to match website structure
      - name: Arrange artifacts
        run: sh scripts/move-artifacts.sh

      # Deploy to github pages!
      - name: Deploy Site 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist

  # Try publishing every package with lerna
  publish-packages:
    name: Conditionally publish packages
    runs-on: ubuntu-latest
    needs: passed-tests
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      # Load up the project
      - uses: actions/cache@v2
        id: restore-project
        with:
          path: ./*
          key: ${{ github.sha }}

      # Load the core build artifacts
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: |
            ./core/dist/*
            ./core/loader/*
          key: ${{ github.sha }}-core

      # Compile packages
      - run: ./node_modules/.bin/lerna run build

      # Run a script which will determine what to publish and how
      - run: sh ./scripts/publish.sh
